baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "BF Website"

[params]
author = "Irena Bojanova"
description = "My Invention, the Bugs Framework (BF)"

#xxx suppress dark mode -- but doe not work
#defaultTheme = "light"
#disableThemeToggle = true